export {
  activeFiltersToLabels,
  ANONYMITY_THRESHOLD,
  averageFavorability,
  buildFilteredScorecardMarkers,
  DASHBOARD_FILTER_FIELDS,
  filterRespondents,
  findWeakestDepartmentCategoryCell,
  getDepartmentCategorySentiment,
  getFilteredCategorySentiment,
  getFilteredENPS,
  getFilteredResponseRate,
  getFilteredSentiment,
  meetsAnonymityThreshold,
  mockDashboardRespondents,
  respondentCount,
} from '@/data/mock/dashboardFilters'
export type { CategorySentiment, DashboardRespondent, ScorecardMarker } from '@/data/mock/dashboardFilters'
export {
  buildMetricTree,
  computeAxisConfig,
  DRIVER_CORRELATION_MATRIX,
  DRIVER_METRICS,
  getCorrelation,
  getDriverImpact,
  getDriverMetricById,
  getDriverOutcomeOptions,
  getEligibleDriverMetrics,
  getMetricFavorability,
  getRespondentMetricScores,
  getYAxisDisclosureLabel,
  normalizeToFavorability,
  pearsonCorrelation,
  pearsonR,
  resolveItemsAtLevel,
} from '@/data/mock/driverAnalysis'
export type {
  AxisConfig,
  DriverMetric,
  DriverMetricKind,
  DriverQuestionType,
  MetricTreeNode,
} from '@/data/mock/driverAnalysis'
